### ISSUE TITLE
Not an issue, a question. 

### ISSUE THREAD

**Issue by arjunthomas** [olumalia/SimpleIPTVRoku#2]
Can we add multiple m3u links?

**Comment by olumalia** [comment]
No sorry it's one list at a time

**Comment by arjunthomas** [comment]
One more question, how can i get rid of the initial screen and use my m3u url as the default right when the channel loads up?
Can you please help me? It's rather Important.
Thank you.

**Comment by olumalia** [comment]
try un-commenting the line on ' enter url here ' i'm unable to test since developer options have been removed

**Comment by arjunthomas** [comment]
Thanks. I'll test it.
